### ISSUE TITLE
Failing WMTS endpoint

### ISSUE THREAD

**Issue by capooti** [geopython/OWSLib#309]
not sure though if it is the format of the xml to be invalid, but:

service.url = http://data.geus.dk/arcgis/rest/services/OneGeologyGlobal/S071_G2500_OneGeology/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

wmts = WebMapTileService(service.url)

Traceback (most recent call last):
File "/webapps/hypermap/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
response = wrapped_callback(request, callback_args, **callback_kwargs)
File "/webapps/hypermap/hypermap/hypermap/aggregator/views.py", line 70, in service_detail
check_service(service)
File "/webapps/hypermap/local/lib/python2.7/site-packages/celery/local.py", line 188, in call
return self._get_current_object()(a, kw)
File "/webapps/hypermap/local/lib/python2.7/site-packages/celery/app/task.py", line 420, in call
return self.run(*args, kwargs)
File "/webapps/hypermap/hypermap/hypermap/aggregator/tasks.py", line 40, in check_service
service.update_layers()
File "/webapps/hypermap/hypermap/hypermap/aggregator/models.py", line 111, in update_layers
update_layers_wmts(self)
File "/webapps/hypermap/hypermap/hypermap/aggregator/models.py", line 348, in update_layers_wmts
wmts = WebMapTileService(service.url)
File "/webapps/hypermap/local/lib/python2.7/site-packages/owslib/wmts.py", line 179, in init
self._buildMetadata(parse_remote_metadata)
File "/webapps/hypermap/local/lib/python2.7/site-packages/owslib/wmts.py", line 199, in _buildMetadata
self.provider = ServiceProvider(serviceprov)
File "/webapps/hypermap/local/lib/python2.7/site-packages/owslib/ows.py", line 80, in init
val = self._root.find(util.nspath('ProviderName', namespace))
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by tomkralidis** [comment]
@capooti fixed in #310.  Can you verify?

**Comment by capooti** [comment]
thanks @tomkralidis!

**Comment by capooti** [comment]
just verified, and it works well. thanks again
