### ISSUE TITLE
Fetch WMTS fails in QGIS Python console but works through QGIS widget

### ISSUE THREAD

**Issue by Guts** [geopython/OWSLib#361]
Copied from: https://hub.qgis.org/issues/16333.

I'm working on my plugin which can add layers from OGC services directly to Map canvas without UI step. So I use owslib with PyQGIS. Trying various WMTS sample (check my script here: https://github.com/isogeo/isogeo-plugin-qgis/blob/master/test/test_wmts.py), I've found a WMTS that works through QGIS integrated widget but not from owslib (see attached screen capture), but not from Python script.

!["With the QGIS integrated widget"](https://hub.qgis.org/attachments/10822/qgis_214_osgeo4w_owslib_wmts.png)

Tested on QGIS 2.14.12 - 64 bits OSGeo4W, W8.1

Just with version parameter (I know, quite useless but...):

```python
wmts = WebMapTileService("http://data.geus.dk/arcgis/rest/services/OneGeologyGlobal/S071_G2500_OneGeology/MapServer/WMTS?request=GetCapabilities", version="1.0.0")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\owslib\wmts.py", line 114, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\owslib\wmts.py", line 133, in _buildMetadata
    self.provider=ServiceProvider(serviceprov)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\owslib\ows.py", line 78, in __init__
    val = self._root.find(util.nspath('ProviderName', namespace))
AttributeError: 'NoneType' object has no attribute 'find'
```

With full parameters:

```python
wmts = WebMapTileService("http://data.geus.dk/arcgis/rest/services/OneGeologyGlobal/S071_G2500_OneGeology/MapServer/WMTS?request=GetCapabilities", version="1.0.0", parse_remote_metadata=0, xml="http://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer/WMTS/1.0.0/WMTSCapabilities.xml")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\owslib\wmts.py", line 102, in __init__
    self._capabilities = reader.readString(xml)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\owslib\wmts.py", line 649, in readString
    return etree.fromstring(st)
  File "C:\OSGEO4~1\apps\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "C:\OSGEO4~1\apps\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\OSGEO4~1\apps\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 5
```

Pointing only on the XML:

```python
wmts = WebMapTileService("http://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer/WMTS/1.0.0/WMTSCapabilities.xml")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\owslib\wmts.py", line 114, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\owslib\wmts.py", line 133, in _buildMetadata
    self.provider=ServiceProvider(serviceprov)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\owslib\ows.py", line 78, in __init__
    val = self._root.find(util.nspath('ProviderName', namespace))
AttributeError: 'NoneType' object has no attribute 'find'
```

Behaviors should be the same, no?

Because of XML parsing error, maybe it's related to https://github.com/geopython/MetaSearch/issues/23?

**Comment by tomkralidis** [comment]
@Guts thanks for the info.  This bug was fixed in OWSLib in https://github.com/geopython/OWSLib/commit/d2d7c60e2bf29f08f2b728ed031e596000aa3432, which is later than the version of OWSLib in QGIS 2.14.x.  I've applied the fix to QGIS 2.14 branch which will appear in 2.14.13 later this month.
