### ISSUE TITLE
[Question] OWSLib can have dots in typename parameter?

### ISSUE THREAD

**Issue by jonnyforestGIS** [geopython/OWSLib#378]
Hi,
the OWSLib support name with dots in typenameparameter?
I test with the default links with underscores but when i do the same test with a WFS service with dots in the typename i have the 404 error response.

The  code:
```python
from owslib.wfs import WebFeatureService

wfs11= WebFeatureService(url='https://ows.isip.ifap.min-agricultura.pt/isip.data/ows', version='1.1.0')

response= wfs11.getfeature(typename='isip.data:ocupacoes.solo.aml.2016jun10')
out= open(r'C:\Users\User1\Desktop\oc_solo_aml_2016jun10.gml', 'wb')
out.write(bytes(response.read(),'UTF-8'))
out.close()
```
The result:
```python
Traceback (most recent call last):
  File "ifap_parcelario.py", line 5, in <module>
    response= wfs11.getfeature(typename='isip.data:ocupacoes.solo.aml.2016jun10'
)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\owslib\feature\wfs110.py", l
ine 243, in getfeature
    username=self.username, password=self.password)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\owslib\util.py", line 189, i
n openURL
    req.raise_for_status()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\requests\models.py", line 90
9, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ows.isip.ifap.min-agricultura.pt/isip.data/wfs?typename=isip.data%3Aocupacoes.solo.aml.2016jun10&propertyname=%2A&version=1.1.0&request=GetFeature&service=WFS
```

Cheers,
João

**Comment by tomkralidis** [comment]
Please post questions to the OWSLib [mailing list](http://lists.osgeo.org/mailman/listinfo/owslib-users). OWSLib's GitHub issues are for **software bugs/enhancements** and related tasks.
