### ISSUE TITLE
WaterML 2.0

### ISSUE THREAD

**Issue by jsanchezfr** [geopython/OWSLib#393]
Issue with parsing WaterML 2.0. Error parsing.
Possible solution:

In file "[path]/Lib/site-packages/owslib/owslib/namespaces.py", line 61:

Change:
        'xsi'   :   'http://www.w3.org/2001/XMLSchema-instance'

To:
        'xsi'   :   'http://www.w3.org/2001/XMLSchema-instance',
        'wml2'  :   'http://www.opengis.net/waterml/2.0'

**Comment by tomkralidis** [comment]
Can you provide a test case that can reproduce the issue?

**Comment by jsanchezfr** [comment]
It's simple. Using the file 'sos_52n_getobservation_wml2_response.xml' from 'tests/resources':
```
from owslib.sos import SensorObservationService
from owslib.swe.observation.sos200 import SOSGetObservationResponse
from owslib.etree import etree
import warnings
warnings.filterwarnings("ignore")
file = open('sos_52n_getobservation_wml2_response.xml')
xml_tree = etree.fromstring(file.read())
parsed_response = SOSGetObservationResponse(xml_tree)
for observations in parsed_response.observations:
  print("featureOfInterest: " + observations.featureOfInterest)
  print("observedProperty: " + observations.observedProperty)    
  print("phenomenonTime: " + str(observations.phenomenonTime))  
  print("procedure: " + observations.procedure)         
  measurement_timeseries = observations.get_result()
  print ("Measure: " + measurement_timeseries.defaultTVPMetadata.uom)
  print ("")  
  for measure in measurement_timeseries.points:
    print("Date: " + str(measure.datetime))
    print("Value: "+ str(measure.value))
    print ("")  
```
Using actual code:
```
Traceback (most recent call last):
  File "E:\ESS\SOS\OWSLib\wml2_test.py", line 8, in <module>
    parsed_response = SOSGetObservationResponse(xml_tree)
  File "E:\programas\python27\lib\site-packages\owslib\swe\observation\sos200.py", line 351, in __init__
    parsed_obs = decoder.decode_observation(obs)
  File "E:\programas\python27\lib\site-packages\owslib\swe\observation\sos200.py", line 385, in decode_observation
    return MeasurementTimeseriesObservation(element)
  File "E:\programas\python27\lib\site-packages\owslib\swe\observation\waterml2.py", line 34, in __init__
    self._parse_result()
  File "E:\programas\python27\lib\site-packages\owslib\swe\observation\waterml2.py", line 58, in _parse_result
    self.result = MeasurementTimeseries(result)
  File "E:\programas\python27\lib\site-packages\owslib\swe\observation\waterml2.py", line 81, in __init__
    self.defaultTVPMetadata = TVPMeasurementMetadata(element.find(
AttributeError: 'NoneType' object has no attribute 'find'
```

With change proposed:
```
featureOfInterest: http://geoviqua.dev.52north.org/stations/Vaisala-WXT520
observedProperty: http://geoviqua.dev.52north.org/properties/AirTemperature
phenomenonTime: start: 2014-07-01 00:01:42+00:00 end: 2014-07-01 01:16:41+00:00
procedure: http://geoviqua.dev.52north.org/procedures/WXT520
Measure: degC

Date: 2014-07-01 00:01:42+00:00
Value: 12.2

Date: 2014-07-01 00:16:42+00:00
Value: 12.3

Date: 2014-07-01 00:31:42+00:00
Value: 12.0

Date: 2014-07-01 00:46:42+00:00
Value: 11.9

Date: 2014-07-01 01:01:42+00:00
Value: 12.1

Date: 2014-07-01 01:16:41+00:00
Value: 12.5
```

The content of file 'sos_52n_getobservation_wml2_response.xml'
```
<?xml version="1.0" encoding="UTF-8"?>
<sos:GetObservationResponse xmlns:sos="http://www.opengis.net/sos/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:om="http://www.opengis.net/om/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:wml2="http://www.opengis.net/waterml/2.0" xsi:schemaLocation="http://www.opengis.net/waterml/2.0 http://schemas.opengis.net/waterml/2.0/waterml2.xsd http://www.opengis.net/sos/2.0 http://schemas.opengis.net/sos/2.0/sosGetObservation.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://www.opengis.net/gmlcov/1.0 http://schemas.opengis.net/gmlcov/1.0/gmlcovAll.xsd wml2dr http://schemas.opengis.net/waterml/2.0/domain-range-informative/timeseries-domain-range.xsd http://www.opengis.net/om/2.0 http://schemas.opengis.net/om/2.0/observation.xsd">
  <sos:observationData>
    <om:OM_Observation gml:id="o_9556E2084893FEC9C6F407458B91F194C86359D6">
      <om:phenomenonTime>
        <gml:TimePeriod gml:id="phenomenonTime_1">
          <gml:beginPosition>2014-07-01T00:01:42.000Z</gml:beginPosition>
          <gml:endPosition>2014-07-01T01:16:41.000Z</gml:endPosition>
        </gml:TimePeriod>
      </om:phenomenonTime>
      <om:resultTime>
        <gml:TimeInstant gml:id="ti_C597E726F2C23BD5C20800061BCDFD0442EF6E44">
          <gml:timePosition>2014-07-01T00:01:42.000Z</gml:timePosition>
        </gml:TimeInstant>
      </om:resultTime>
      <om:procedure xlink:href="http://geoviqua.dev.52north.org/procedures/WXT520"/>
      <om:observedProperty xlink:href="http://geoviqua.dev.52north.org/properties/AirTemperature"/>
      <om:featureOfInterest xlink:href="http://geoviqua.dev.52north.org/stations/Vaisala-WXT520" xlink:title="Vaisala_WXT520"/>
      <om:result>
        <wml2:MeasurementTimeseries gml:id="timeseries.1">
          <wml2:metadata>
            <wml2:TimeseriesMetadata>
              <wml2:temporalExtent xlink:href="#phenomenonTime_1"/>
            </wml2:TimeseriesMetadata>
          </wml2:metadata>
          <wml2:defaultPointMetadata>
            <wml2:DefaultTVPMeasurementMetadata>
              <wml2:uom code="degC"/>
              <wml2:interpolationType xlink:href="http://www.opengis.net/def/timeseriesType/WaterML/2.0/continuous" xlink:title="Instantaneous"/>
            </wml2:DefaultTVPMeasurementMetadata>
          </wml2:defaultPointMetadata>
          <wml2:point>
            <wml2:MeasurementTVP>
              <wml2:time>2014-07-01T00:01:42.000Z</wml2:time>
              <wml2:value>12.2</wml2:value>
            </wml2:MeasurementTVP>
          </wml2:point>
          <wml2:point>
            <wml2:MeasurementTVP>
              <wml2:time>2014-07-01T00:16:42.000Z</wml2:time>
              <wml2:value>12.3</wml2:value>
            </wml2:MeasurementTVP>
          </wml2:point>
          <wml2:point>
            <wml2:MeasurementTVP>
              <wml2:time>2014-07-01T00:31:42.000Z</wml2:time>
              <wml2:value>12.0</wml2:value>
            </wml2:MeasurementTVP>
          </wml2:point>
          <wml2:point>
            <wml2:MeasurementTVP>
              <wml2:time>2014-07-01T00:46:42.000Z</wml2:time>
              <wml2:value>11.9</wml2:value>
            </wml2:MeasurementTVP>
          </wml2:point>
          <wml2:point>
            <wml2:MeasurementTVP>
              <wml2:time>2014-07-01T01:01:42.000Z</wml2:time>
              <wml2:value>12.1</wml2:value>
            </wml2:MeasurementTVP>
          </wml2:point>
          <wml2:point>
            <wml2:MeasurementTVP>
              <wml2:time>2014-07-01T01:16:41.000Z</wml2:time>
              <wml2:value>12.5</wml2:value>
            </wml2:MeasurementTVP>
          </wml2:point>
        </wml2:MeasurementTimeseries>
      </om:result>
    </om:OM_Observation>
  </sos:observationData>
</sos:GetObservationResponse>
```

**Comment by tomkralidis** [comment]
Thanks for the report.  Can you issue a pull request with these changes then?

**Comment by jsanchezfr** [comment]
I'm new in Github, I'm neither a member of the team or collaborator, so I've not permissions to publish my branch.

**Comment by tomkralidis** [comment]
Hi @jsanchezfr you can fork OWSLib and push changes to your fork, followed by a pull request to OWSLib (https://help.github.com/articles/creating-a-pull-request/)

**Comment by jsanchezfr** [comment]
I did it! Thanks for the help.

**Comment by cehbrecht** [comment]
Seems to be fixed by PR #394.
