### ISSUE TITLE
doctest sos_10_ndbc_getobservation.txt is failing

### ISSUE THREAD

**Issue by cehbrecht** [geopython/OWSLib#481]
This test is failing:
`tests/doctests/sos_10_ndbc_getobservation.txt`

Error message:
```
__________________ [doctest] sos_10_ndbc_getobservation.txt ___________________
     >>> response = ndbc.describe_sensor(procedure=procedure, outputFormat=outputFormat)     #doctest: +IGNORE_EXCEPTION_DETAIL
     Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
     ServiceException: 'foobar'
 
     # Valid request
 
     >>> procedure = ndbc.offerings[1].procedures[0]
     >>> outputFormat = ndbc.get_operation_by_name('DescribeSensor').parameters['outputFormat']['values'][0]
     >>> response = ndbc.describe_sensor(procedure=procedure, outputFormat=outputFormat)
UNEXPECTED EXCEPTION: ServiceException('No data found for this station',)
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs
  File "<doctest sos_10_ndbc_getobservation.txt[26]>", line 1, in <module>
  File "/home/travis/build/geopython/OWSLib/owslib/swe/observation/sos100.py", line 140, in describe_sensor
    response = openURL(base_url, data, method, username=self.username, password=self.password, **url_kwargs).read()
  File "/home/travis/build/geopython/OWSLib/owslib/util.py", line 216, in openURL
    raise ServiceException('\n'.join([str(t).strip() for t in serviceException.itertext() if str(t).strip()]))
ServiceException: No data found for this station
```

**Comment by cehbrecht** [comment]
Test disable for now by PR #482.

Needs to be converted to "normal" test and preferable as offline test.
