### ISSUE TITLE
CatalogueServiceWeb.getrecords2 TypeError when using threading.Thread

### ISSUE THREAD

**Issue by jankovicgd** [geopython/OWSLib#569]
I am trying to get the results from a csw faster by using threads. However I get following errors from the threads:

```
Exception in thread Thread-61:
Traceback (most recent call last):
  File "/home/nikola/miniconda3/envs/owslib/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/nikola/miniconda3/envs/owslib/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-37-7f148a427f54>", line 8, in loop_csw
    startposition=0 if next_record == 1 else next_record)
  File "/home/nikola/miniconda3/envs/owslib/lib/python3.7/site-packages/owslib/csw.py", line 376, in getrecords2
    self._invoke()
  File "/home/nikola/miniconda3/envs/owslib/lib/python3.7/site-packages/owslib/csw.py", line 663, in _invoke
    self.request = cleanup_namespaces(self.request)
  File "/home/nikola/miniconda3/envs/owslib/lib/python3.7/site-packages/owslib/util.py", line 257, in cleanup_namespaces
    etree.cleanup_namespaces(element)
  File "src/lxml/cleanup.pxi", line 17, in lxml.etree.cleanup_namespaces
  File "src/lxml/apihelpers.pxi", line 61, in lxml.etree._rootNodeOrRaise
TypeError: Invalid input object: bytes
```

Considering the following code:

```python
from owslib.csw import CatalogueServiceWeb
from owslib.fes import PropertyIsEqualTo, And
from threading import Thread
from collections import OrderedDict

query = And([PropertyIsEqualTo('eodc:variable_name', 'SIG0'),
             PropertyIsEqualTo('eodc:polarisation', 'VV')])
max_records = 1000
no_datasets_to_download = 4430
md_records = OrderedDict()
csw = CatalogueServiceWeb('https://csw-acube.eodc.eu')
threads = []
def loop_csw(query, max_records, next_record):
    csw.getrecords2([query],
                    maxrecords=max_records,
                    esn='full',
                    outputschema='http://www.isotc211.org/2005/gmd',
                    startposition=0 if next_record == 1 else next_record)
    md_records.update(csw.records)

for next_record in range(0, no_datasets_to_download, max_records):
    thr = Thread(target=loop_csw, args=(query, max_records, next_record))
    threads.append(thr)

[t.start() for t in threads]
[t.join() for t in threads]
    
print(len(md_records)) # the length is always varied and should be == no_datasets_to_download
```

Is this intended? If so, the only solution I have so far is to wait which can get very slow for larger requests. Any other ideas?

**Comment by tomkralidis** [comment]
@jankovicgd thanks for reporting.  I cannot reproduce this in Python 2 or 3 for that matter.  Which version of Python are you testing this against?

**Comment by jankovicgd** [comment]
Sorry for the late reply. It completely slipped my mind I was attempting to run this.

Just tried with python 3.7.3 and owslib 0.17.1. Running from a conda environment.
