### ISSUE TITLE
WebMapTileService fails to parse a document with not ascii chars in titles

### ISSUE THREAD

**Issue by capooti** [geopython/OWSLib#616]
When trying to parse WMTS layers from this service:
https://gsi-cyberjapan.github.io/experimental_wmts/gsitiles_wmts.xml

I am getting the following error:

```
ows = WebMapTileService(self.url)

'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/home/ubuntu/wm-2.10.x/hypermap/hypermap/aggregator/models.py", line 369, in check_available
    ows = WebMapTileService(self.url)
  File "/home/ubuntu/wm-2.10.x/hypermap/env/local/lib/python2.7/site-packages/owslib/wmts.py", line 191, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "/home/ubuntu/wm-2.10.x/hypermap/env/local/lib/python2.7/site-packages/owslib/wmts.py", line 210, in _buildMetadata
    self.identification = ServiceIdentification(serviceident)
  File "/home/ubuntu/wm-2.10.x/hypermap/env/local/lib/python2.7/site-packages/owslib/ows.py", line 54, in __init__
    val = self._root.find(util.nspath('Title', namespace))
AttributeError: 'NoneType' object has no attribute 'find'
Service checked in 0.79322 seconds, status is False
```

thanks

**Comment by tomkralidis** [comment]
Fixed in #617
