### ISSUE TITLE
OWSLib Throws Connection Errors when Retreiving WMS GetFeatureInfo (for GetCapabilities Service Connection)

### ISSUE THREAD

**Issue by Skleev** [geopython/OWSLib#731]
Hi,

I encountered a Read Timeout for the first time (yesterday around 1 PM eastern) and I was wondering if there's any internal error handling in OWSLib for handling these specific types of errors, and if not what would be the best approach to catch any of these errors potentially related to downtime from the API?

The stack Trace is below:

```Requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='geo.weather.gc.ca', port=443): Read timed out. (read timeout=30)[13:02] Traceback (most recent call last):
  File "msc_geomet_client.py", line 81, in <module>
    probability_5mm_or_more = request(layer)
  File "msc_geomet_client.py", line 68, in request
    time=str(timestep.isoformat()) + 'Z'
  File "/usr/lib/python3/dist-packages/owslib/map/wms130.py", line 385, in getfeatureinfo
    u = openURL(base_url, data, method, username=self.username, password=self.password, timeout=timeout or self.timeout)
  File "/usr/lib/python3/dist-packages/owslib/util.py", line 180, in openURL
    **rkwargs)
  File "/home/j/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/j/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/j/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/j/.local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='geo.weather.gc.ca', port=443): Read timed out. (read timeout=30)
```

**Comment by Skleev** [comment]
Closed

**Comment by Skleev** [comment]
Re Opened

**Comment by Skleev** [comment]
Closed
