### ISSUE TITLE
Problem with parsing CRS84 srs identifier in WFS  capabilities

### ISSUE THREAD

**Issue by petermozolik** [geopython/OWSLib#896]
Parsing WFS 2.0.0. GetCapabilities response containing valid CRS identifier "https://www.opengis.net/def/crs/OGC/1.3/CRS84" (check this example  [GetCapabilities response](https://www.nlcsk.org/mgs/services/InspireWFS/jprl_wfs/MapServer/WFSServer?service=WFS&version=2.0.0&REQUEST=GetCapabilities)) currently results in error/exception:

<details>
<summary>Exception raised when parsing https://www.opengis.net/def/crs/OGC/1.3/CRS84 identifier</summary>

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/./geoportal_api/routers/datasets.py", line 228, in get_dataset_with_resources
    source = get_wfs_source(db=db, endpoint=res.url)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/./geoportal_api/utils/ows.py", line 320, in get_wfs_source
    wfs, wfs_model = get_service_and_model(
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/./geoportal_api/utils/ows.py", line 113, in get_service_and_model
    _service = service(endpoint, **_args)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/owslib/wfs.py", line 56, in WebFeatureService
    return wfs200.WebFeatureService_2_0_0(
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/owslib/feature/wfs200.py", line 77, in __new__
    obj.__init__(
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/owslib/feature/wfs200.py", line 129, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/owslib/feature/wfs200.py", line 193, in _buildMetadata
    cm = ContentMetadata(
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/owslib/feature/wfs200.py", line 558, in __init__
    self.crsOptions = [
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/owslib/feature/wfs200.py", line 559, in <listcomp>
    Crs(srs.text) for srs in elem.findall(nspath("OtherCRS", ns=WFS_NAMESPACE))
  File "/home/mozolik/Work/mzpsr/geocloud.sk/applications/geoportal-api/.venv/lib/python3.9/site-packages/owslib/crs.py", line 1753, in __init__
    self.code = int(vals[-1])
ValueError: invalid literal for int() with base 10: 'CRS84'
```
</details>

The exceptions is caused by code in `initializer` of `CRS` class (https://github.com/geopython/OWSLib/blob/master/owslib/crs.py#L1749C1-L1753C38)

```
        if self.id.find('/def/crs/') != -1:  # URI Style 1
            self.encoding = "uri"
            vals = self.id.split('/')
            self.authority = vals[5].upper()
            self.code = int(vals[-1])
```
in which `self.code` is assumed to be integer hence `self.code = int(vals[-1])`, in case of CRS identifier "https://www.opengis.net/def/crs/OGC/1.3/CRS84"  (whic is valid CRS identifier) the value of `self.code` happend to be a `CRS84` which is not possible to cast in integer -> thus exception `ValueError` is raised

Perhaps, the solution would be to wrap line `self.code = int(vals[-1])` in exception handling block similar to the code following few lines bellow this actual code (see https://github.com/geopython/OWSLib/blob/master/owslib/crs.py#L1776C1-L1780C39) like this:
```
        if self.id.find('/def/crs/') != -1:  # URI Style 1
            self.encoding = "uri"
            vals = self.id.split('/')
            self.authority = vals[5].upper()
            try:
                self.code = int(values[-1])
            except Exception:
                self.code = values[-1]
```
I'm not sure about wider consequences of proposed chage ...

**Comment by fmigneault** [comment]
Fixed by Depends on https://github.com/geopython/OWSLib/pull/897

**Comment by petermozolik** [comment]
@fmigneault thanks for your fix, i dont understand release cycle/strategy of OWSLib, so please when may I expect this change to be released also on PyPI (https://pypi.org/project/OWSLib/)?

**Comment by fmigneault** [comment]
@petermozolik I'm not in charge of the releases, but @tomkralidis was planing to do one sometime next week (https://github.com/geopython/OWSLib/pull/898#issuecomment-1789826012).

**Comment by petermozolik** [comment]
@fmigneault thank you for your quick response, i'll be checking release next week
